# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files/CMake/bin/cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:/RAOP-Player-bindings

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:/RAOP-Player-bindings

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:/Program Files/CMake/bin/cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:/RAOP-Player-bindings/CMakeFiles E:/RAOP-Player-bindings//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:/RAOP-Player-bindings/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libraop

# Build rule for target.
libraop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libraop
.PHONY : libraop

# fast build rule for target.
libraop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/build
.PHONY : libraop/fast

python/bindings.obj: python/bindings.cpp.obj
.PHONY : python/bindings.obj

# target to build an object file
python/bindings.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/python/bindings.cpp.obj
.PHONY : python/bindings.cpp.obj

python/bindings.i: python/bindings.cpp.i
.PHONY : python/bindings.i

# target to preprocess a source file
python/bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/python/bindings.cpp.i
.PHONY : python/bindings.cpp.i

python/bindings.s: python/bindings.cpp.s
.PHONY : python/bindings.s

# target to generate assembly for a file
python/bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/python/bindings.cpp.s
.PHONY : python/bindings.cpp.s

src/aexcl_lib.obj: src/aexcl_lib.c.obj
.PHONY : src/aexcl_lib.obj

# target to build an object file
src/aexcl_lib.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/aexcl_lib.c.obj
.PHONY : src/aexcl_lib.c.obj

src/aexcl_lib.i: src/aexcl_lib.c.i
.PHONY : src/aexcl_lib.i

# target to preprocess a source file
src/aexcl_lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/aexcl_lib.c.i
.PHONY : src/aexcl_lib.c.i

src/aexcl_lib.s: src/aexcl_lib.c.s
.PHONY : src/aexcl_lib.s

# target to generate assembly for a file
src/aexcl_lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/aexcl_lib.c.s
.PHONY : src/aexcl_lib.c.s

src/alac_wrapper.obj: src/alac_wrapper.cpp.obj
.PHONY : src/alac_wrapper.obj

# target to build an object file
src/alac_wrapper.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/alac_wrapper.cpp.obj
.PHONY : src/alac_wrapper.cpp.obj

src/alac_wrapper.i: src/alac_wrapper.cpp.i
.PHONY : src/alac_wrapper.i

# target to preprocess a source file
src/alac_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/alac_wrapper.cpp.i
.PHONY : src/alac_wrapper.cpp.i

src/alac_wrapper.s: src/alac_wrapper.cpp.s
.PHONY : src/alac_wrapper.s

# target to generate assembly for a file
src/alac_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/alac_wrapper.cpp.s
.PHONY : src/alac_wrapper.cpp.s

src/base64.obj: src/base64.c.obj
.PHONY : src/base64.obj

# target to build an object file
src/base64.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/base64.c.obj
.PHONY : src/base64.c.obj

src/base64.i: src/base64.c.i
.PHONY : src/base64.i

# target to preprocess a source file
src/base64.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/base64.c.i
.PHONY : src/base64.c.i

src/base64.s: src/base64.c.s
.PHONY : src/base64.s

# target to generate assembly for a file
src/base64.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/base64.c.s
.PHONY : src/base64.c.s

src/dmap.obj: src/dmap.c.obj
.PHONY : src/dmap.obj

# target to build an object file
src/dmap.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/dmap.c.obj
.PHONY : src/dmap.c.obj

src/dmap.i: src/dmap.c.i
.PHONY : src/dmap.i

# target to preprocess a source file
src/dmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/dmap.c.i
.PHONY : src/dmap.c.i

src/dmap.s: src/dmap.c.s
.PHONY : src/dmap.s

# target to generate assembly for a file
src/dmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/dmap.c.s
.PHONY : src/dmap.c.s

src/raop_client.obj: src/raop_client.c.obj
.PHONY : src/raop_client.obj

# target to build an object file
src/raop_client.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/raop_client.c.obj
.PHONY : src/raop_client.c.obj

src/raop_client.i: src/raop_client.c.i
.PHONY : src/raop_client.i

# target to preprocess a source file
src/raop_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/raop_client.c.i
.PHONY : src/raop_client.c.i

src/raop_client.s: src/raop_client.c.s
.PHONY : src/raop_client.s

# target to generate assembly for a file
src/raop_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/raop_client.c.s
.PHONY : src/raop_client.c.s

src/rtsp_client.obj: src/rtsp_client.c.obj
.PHONY : src/rtsp_client.obj

# target to build an object file
src/rtsp_client.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/rtsp_client.c.obj
.PHONY : src/rtsp_client.c.obj

src/rtsp_client.i: src/rtsp_client.c.i
.PHONY : src/rtsp_client.i

# target to preprocess a source file
src/rtsp_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/rtsp_client.c.i
.PHONY : src/rtsp_client.c.i

src/rtsp_client.s: src/rtsp_client.c.s
.PHONY : src/rtsp_client.s

# target to generate assembly for a file
src/rtsp_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/rtsp_client.c.s
.PHONY : src/rtsp_client.c.s

src/srp.obj: src/srp.c.obj
.PHONY : src/srp.obj

# target to build an object file
src/srp.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/srp.c.obj
.PHONY : src/srp.c.obj

src/srp.i: src/srp.c.i
.PHONY : src/srp.i

# target to preprocess a source file
src/srp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/srp.c.i
.PHONY : src/srp.c.i

src/srp.s: src/srp.c.s
.PHONY : src/srp.s

# target to generate assembly for a file
src/srp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/src/srp.c.s
.PHONY : src/srp.c.s

tools/log_util.obj: tools/log_util.c.obj
.PHONY : tools/log_util.obj

# target to build an object file
tools/log_util.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/tools/log_util.c.obj
.PHONY : tools/log_util.c.obj

tools/log_util.i: tools/log_util.c.i
.PHONY : tools/log_util.i

# target to preprocess a source file
tools/log_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/tools/log_util.c.i
.PHONY : tools/log_util.c.i

tools/log_util.s: tools/log_util.c.s
.PHONY : tools/log_util.s

# target to generate assembly for a file
tools/log_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/tools/log_util.c.s
.PHONY : tools/log_util.c.s

vendor/alac/codec/ALACBitUtilities.obj: vendor/alac/codec/ALACBitUtilities.c.obj
.PHONY : vendor/alac/codec/ALACBitUtilities.obj

# target to build an object file
vendor/alac/codec/ALACBitUtilities.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ALACBitUtilities.c.obj
.PHONY : vendor/alac/codec/ALACBitUtilities.c.obj

vendor/alac/codec/ALACBitUtilities.i: vendor/alac/codec/ALACBitUtilities.c.i
.PHONY : vendor/alac/codec/ALACBitUtilities.i

# target to preprocess a source file
vendor/alac/codec/ALACBitUtilities.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ALACBitUtilities.c.i
.PHONY : vendor/alac/codec/ALACBitUtilities.c.i

vendor/alac/codec/ALACBitUtilities.s: vendor/alac/codec/ALACBitUtilities.c.s
.PHONY : vendor/alac/codec/ALACBitUtilities.s

# target to generate assembly for a file
vendor/alac/codec/ALACBitUtilities.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ALACBitUtilities.c.s
.PHONY : vendor/alac/codec/ALACBitUtilities.c.s

vendor/alac/codec/ALACDecoder.obj: vendor/alac/codec/ALACDecoder.cpp.obj
.PHONY : vendor/alac/codec/ALACDecoder.obj

# target to build an object file
vendor/alac/codec/ALACDecoder.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ALACDecoder.cpp.obj
.PHONY : vendor/alac/codec/ALACDecoder.cpp.obj

vendor/alac/codec/ALACDecoder.i: vendor/alac/codec/ALACDecoder.cpp.i
.PHONY : vendor/alac/codec/ALACDecoder.i

# target to preprocess a source file
vendor/alac/codec/ALACDecoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ALACDecoder.cpp.i
.PHONY : vendor/alac/codec/ALACDecoder.cpp.i

vendor/alac/codec/ALACDecoder.s: vendor/alac/codec/ALACDecoder.cpp.s
.PHONY : vendor/alac/codec/ALACDecoder.s

# target to generate assembly for a file
vendor/alac/codec/ALACDecoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ALACDecoder.cpp.s
.PHONY : vendor/alac/codec/ALACDecoder.cpp.s

vendor/alac/codec/ALACEncoder.obj: vendor/alac/codec/ALACEncoder.cpp.obj
.PHONY : vendor/alac/codec/ALACEncoder.obj

# target to build an object file
vendor/alac/codec/ALACEncoder.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ALACEncoder.cpp.obj
.PHONY : vendor/alac/codec/ALACEncoder.cpp.obj

vendor/alac/codec/ALACEncoder.i: vendor/alac/codec/ALACEncoder.cpp.i
.PHONY : vendor/alac/codec/ALACEncoder.i

# target to preprocess a source file
vendor/alac/codec/ALACEncoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ALACEncoder.cpp.i
.PHONY : vendor/alac/codec/ALACEncoder.cpp.i

vendor/alac/codec/ALACEncoder.s: vendor/alac/codec/ALACEncoder.cpp.s
.PHONY : vendor/alac/codec/ALACEncoder.s

# target to generate assembly for a file
vendor/alac/codec/ALACEncoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ALACEncoder.cpp.s
.PHONY : vendor/alac/codec/ALACEncoder.cpp.s

vendor/alac/codec/EndianPortable.obj: vendor/alac/codec/EndianPortable.c.obj
.PHONY : vendor/alac/codec/EndianPortable.obj

# target to build an object file
vendor/alac/codec/EndianPortable.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/EndianPortable.c.obj
.PHONY : vendor/alac/codec/EndianPortable.c.obj

vendor/alac/codec/EndianPortable.i: vendor/alac/codec/EndianPortable.c.i
.PHONY : vendor/alac/codec/EndianPortable.i

# target to preprocess a source file
vendor/alac/codec/EndianPortable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/EndianPortable.c.i
.PHONY : vendor/alac/codec/EndianPortable.c.i

vendor/alac/codec/EndianPortable.s: vendor/alac/codec/EndianPortable.c.s
.PHONY : vendor/alac/codec/EndianPortable.s

# target to generate assembly for a file
vendor/alac/codec/EndianPortable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/EndianPortable.c.s
.PHONY : vendor/alac/codec/EndianPortable.c.s

vendor/alac/codec/ag_dec.obj: vendor/alac/codec/ag_dec.c.obj
.PHONY : vendor/alac/codec/ag_dec.obj

# target to build an object file
vendor/alac/codec/ag_dec.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ag_dec.c.obj
.PHONY : vendor/alac/codec/ag_dec.c.obj

vendor/alac/codec/ag_dec.i: vendor/alac/codec/ag_dec.c.i
.PHONY : vendor/alac/codec/ag_dec.i

# target to preprocess a source file
vendor/alac/codec/ag_dec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ag_dec.c.i
.PHONY : vendor/alac/codec/ag_dec.c.i

vendor/alac/codec/ag_dec.s: vendor/alac/codec/ag_dec.c.s
.PHONY : vendor/alac/codec/ag_dec.s

# target to generate assembly for a file
vendor/alac/codec/ag_dec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ag_dec.c.s
.PHONY : vendor/alac/codec/ag_dec.c.s

vendor/alac/codec/ag_enc.obj: vendor/alac/codec/ag_enc.c.obj
.PHONY : vendor/alac/codec/ag_enc.obj

# target to build an object file
vendor/alac/codec/ag_enc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ag_enc.c.obj
.PHONY : vendor/alac/codec/ag_enc.c.obj

vendor/alac/codec/ag_enc.i: vendor/alac/codec/ag_enc.c.i
.PHONY : vendor/alac/codec/ag_enc.i

# target to preprocess a source file
vendor/alac/codec/ag_enc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ag_enc.c.i
.PHONY : vendor/alac/codec/ag_enc.c.i

vendor/alac/codec/ag_enc.s: vendor/alac/codec/ag_enc.c.s
.PHONY : vendor/alac/codec/ag_enc.s

# target to generate assembly for a file
vendor/alac/codec/ag_enc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/ag_enc.c.s
.PHONY : vendor/alac/codec/ag_enc.c.s

vendor/alac/codec/dp_dec.obj: vendor/alac/codec/dp_dec.c.obj
.PHONY : vendor/alac/codec/dp_dec.obj

# target to build an object file
vendor/alac/codec/dp_dec.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/dp_dec.c.obj
.PHONY : vendor/alac/codec/dp_dec.c.obj

vendor/alac/codec/dp_dec.i: vendor/alac/codec/dp_dec.c.i
.PHONY : vendor/alac/codec/dp_dec.i

# target to preprocess a source file
vendor/alac/codec/dp_dec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/dp_dec.c.i
.PHONY : vendor/alac/codec/dp_dec.c.i

vendor/alac/codec/dp_dec.s: vendor/alac/codec/dp_dec.c.s
.PHONY : vendor/alac/codec/dp_dec.s

# target to generate assembly for a file
vendor/alac/codec/dp_dec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/dp_dec.c.s
.PHONY : vendor/alac/codec/dp_dec.c.s

vendor/alac/codec/dp_enc.obj: vendor/alac/codec/dp_enc.c.obj
.PHONY : vendor/alac/codec/dp_enc.obj

# target to build an object file
vendor/alac/codec/dp_enc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/dp_enc.c.obj
.PHONY : vendor/alac/codec/dp_enc.c.obj

vendor/alac/codec/dp_enc.i: vendor/alac/codec/dp_enc.c.i
.PHONY : vendor/alac/codec/dp_enc.i

# target to preprocess a source file
vendor/alac/codec/dp_enc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/dp_enc.c.i
.PHONY : vendor/alac/codec/dp_enc.c.i

vendor/alac/codec/dp_enc.s: vendor/alac/codec/dp_enc.c.s
.PHONY : vendor/alac/codec/dp_enc.s

# target to generate assembly for a file
vendor/alac/codec/dp_enc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/dp_enc.c.s
.PHONY : vendor/alac/codec/dp_enc.c.s

vendor/alac/codec/matrix_dec.obj: vendor/alac/codec/matrix_dec.c.obj
.PHONY : vendor/alac/codec/matrix_dec.obj

# target to build an object file
vendor/alac/codec/matrix_dec.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/matrix_dec.c.obj
.PHONY : vendor/alac/codec/matrix_dec.c.obj

vendor/alac/codec/matrix_dec.i: vendor/alac/codec/matrix_dec.c.i
.PHONY : vendor/alac/codec/matrix_dec.i

# target to preprocess a source file
vendor/alac/codec/matrix_dec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/matrix_dec.c.i
.PHONY : vendor/alac/codec/matrix_dec.c.i

vendor/alac/codec/matrix_dec.s: vendor/alac/codec/matrix_dec.c.s
.PHONY : vendor/alac/codec/matrix_dec.s

# target to generate assembly for a file
vendor/alac/codec/matrix_dec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/matrix_dec.c.s
.PHONY : vendor/alac/codec/matrix_dec.c.s

vendor/alac/codec/matrix_enc.obj: vendor/alac/codec/matrix_enc.c.obj
.PHONY : vendor/alac/codec/matrix_enc.obj

# target to build an object file
vendor/alac/codec/matrix_enc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/matrix_enc.c.obj
.PHONY : vendor/alac/codec/matrix_enc.c.obj

vendor/alac/codec/matrix_enc.i: vendor/alac/codec/matrix_enc.c.i
.PHONY : vendor/alac/codec/matrix_enc.i

# target to preprocess a source file
vendor/alac/codec/matrix_enc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/matrix_enc.c.i
.PHONY : vendor/alac/codec/matrix_enc.c.i

vendor/alac/codec/matrix_enc.s: vendor/alac/codec/matrix_enc.c.s
.PHONY : vendor/alac/codec/matrix_enc.s

# target to generate assembly for a file
vendor/alac/codec/matrix_enc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/alac/codec/matrix_enc.c.s
.PHONY : vendor/alac/codec/matrix_enc.c.s

vendor/curve25519/source/curve25519_dh.obj: vendor/curve25519/source/curve25519_dh.c.obj
.PHONY : vendor/curve25519/source/curve25519_dh.obj

# target to build an object file
vendor/curve25519/source/curve25519_dh.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_dh.c.obj
.PHONY : vendor/curve25519/source/curve25519_dh.c.obj

vendor/curve25519/source/curve25519_dh.i: vendor/curve25519/source/curve25519_dh.c.i
.PHONY : vendor/curve25519/source/curve25519_dh.i

# target to preprocess a source file
vendor/curve25519/source/curve25519_dh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_dh.c.i
.PHONY : vendor/curve25519/source/curve25519_dh.c.i

vendor/curve25519/source/curve25519_dh.s: vendor/curve25519/source/curve25519_dh.c.s
.PHONY : vendor/curve25519/source/curve25519_dh.s

# target to generate assembly for a file
vendor/curve25519/source/curve25519_dh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_dh.c.s
.PHONY : vendor/curve25519/source/curve25519_dh.c.s

vendor/curve25519/source/curve25519_mehdi.obj: vendor/curve25519/source/curve25519_mehdi.c.obj
.PHONY : vendor/curve25519/source/curve25519_mehdi.obj

# target to build an object file
vendor/curve25519/source/curve25519_mehdi.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_mehdi.c.obj
.PHONY : vendor/curve25519/source/curve25519_mehdi.c.obj

vendor/curve25519/source/curve25519_mehdi.i: vendor/curve25519/source/curve25519_mehdi.c.i
.PHONY : vendor/curve25519/source/curve25519_mehdi.i

# target to preprocess a source file
vendor/curve25519/source/curve25519_mehdi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_mehdi.c.i
.PHONY : vendor/curve25519/source/curve25519_mehdi.c.i

vendor/curve25519/source/curve25519_mehdi.s: vendor/curve25519/source/curve25519_mehdi.c.s
.PHONY : vendor/curve25519/source/curve25519_mehdi.s

# target to generate assembly for a file
vendor/curve25519/source/curve25519_mehdi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_mehdi.c.s
.PHONY : vendor/curve25519/source/curve25519_mehdi.c.s

vendor/curve25519/source/curve25519_order.obj: vendor/curve25519/source/curve25519_order.c.obj
.PHONY : vendor/curve25519/source/curve25519_order.obj

# target to build an object file
vendor/curve25519/source/curve25519_order.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_order.c.obj
.PHONY : vendor/curve25519/source/curve25519_order.c.obj

vendor/curve25519/source/curve25519_order.i: vendor/curve25519/source/curve25519_order.c.i
.PHONY : vendor/curve25519/source/curve25519_order.i

# target to preprocess a source file
vendor/curve25519/source/curve25519_order.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_order.c.i
.PHONY : vendor/curve25519/source/curve25519_order.c.i

vendor/curve25519/source/curve25519_order.s: vendor/curve25519/source/curve25519_order.c.s
.PHONY : vendor/curve25519/source/curve25519_order.s

# target to generate assembly for a file
vendor/curve25519/source/curve25519_order.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_order.c.s
.PHONY : vendor/curve25519/source/curve25519_order.c.s

vendor/curve25519/source/curve25519_utils.obj: vendor/curve25519/source/curve25519_utils.c.obj
.PHONY : vendor/curve25519/source/curve25519_utils.obj

# target to build an object file
vendor/curve25519/source/curve25519_utils.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_utils.c.obj
.PHONY : vendor/curve25519/source/curve25519_utils.c.obj

vendor/curve25519/source/curve25519_utils.i: vendor/curve25519/source/curve25519_utils.c.i
.PHONY : vendor/curve25519/source/curve25519_utils.i

# target to preprocess a source file
vendor/curve25519/source/curve25519_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_utils.c.i
.PHONY : vendor/curve25519/source/curve25519_utils.c.i

vendor/curve25519/source/curve25519_utils.s: vendor/curve25519/source/curve25519_utils.c.s
.PHONY : vendor/curve25519/source/curve25519_utils.s

# target to generate assembly for a file
vendor/curve25519/source/curve25519_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/curve25519_utils.c.s
.PHONY : vendor/curve25519/source/curve25519_utils.c.s

vendor/curve25519/source/custom_blind.obj: vendor/curve25519/source/custom_blind.c.obj
.PHONY : vendor/curve25519/source/custom_blind.obj

# target to build an object file
vendor/curve25519/source/custom_blind.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/custom_blind.c.obj
.PHONY : vendor/curve25519/source/custom_blind.c.obj

vendor/curve25519/source/custom_blind.i: vendor/curve25519/source/custom_blind.c.i
.PHONY : vendor/curve25519/source/custom_blind.i

# target to preprocess a source file
vendor/curve25519/source/custom_blind.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/custom_blind.c.i
.PHONY : vendor/curve25519/source/custom_blind.c.i

vendor/curve25519/source/custom_blind.s: vendor/curve25519/source/custom_blind.c.s
.PHONY : vendor/curve25519/source/custom_blind.s

# target to generate assembly for a file
vendor/curve25519/source/custom_blind.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/custom_blind.c.s
.PHONY : vendor/curve25519/source/custom_blind.c.s

vendor/curve25519/source/ed25519_sign.obj: vendor/curve25519/source/ed25519_sign.c.obj
.PHONY : vendor/curve25519/source/ed25519_sign.obj

# target to build an object file
vendor/curve25519/source/ed25519_sign.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/ed25519_sign.c.obj
.PHONY : vendor/curve25519/source/ed25519_sign.c.obj

vendor/curve25519/source/ed25519_sign.i: vendor/curve25519/source/ed25519_sign.c.i
.PHONY : vendor/curve25519/source/ed25519_sign.i

# target to preprocess a source file
vendor/curve25519/source/ed25519_sign.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/ed25519_sign.c.i
.PHONY : vendor/curve25519/source/ed25519_sign.c.i

vendor/curve25519/source/ed25519_sign.s: vendor/curve25519/source/ed25519_sign.c.s
.PHONY : vendor/curve25519/source/ed25519_sign.s

# target to generate assembly for a file
vendor/curve25519/source/ed25519_sign.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/ed25519_sign.c.s
.PHONY : vendor/curve25519/source/ed25519_sign.c.s

vendor/curve25519/source/ed25519_verify.obj: vendor/curve25519/source/ed25519_verify.c.obj
.PHONY : vendor/curve25519/source/ed25519_verify.obj

# target to build an object file
vendor/curve25519/source/ed25519_verify.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/ed25519_verify.c.obj
.PHONY : vendor/curve25519/source/ed25519_verify.c.obj

vendor/curve25519/source/ed25519_verify.i: vendor/curve25519/source/ed25519_verify.c.i
.PHONY : vendor/curve25519/source/ed25519_verify.i

# target to preprocess a source file
vendor/curve25519/source/ed25519_verify.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/ed25519_verify.c.i
.PHONY : vendor/curve25519/source/ed25519_verify.c.i

vendor/curve25519/source/ed25519_verify.s: vendor/curve25519/source/ed25519_verify.c.s
.PHONY : vendor/curve25519/source/ed25519_verify.s

# target to generate assembly for a file
vendor/curve25519/source/ed25519_verify.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/curve25519/source/ed25519_verify.c.s
.PHONY : vendor/curve25519/source/ed25519_verify.c.s

vendor/libplist/libcnary/cnary.obj: vendor/libplist/libcnary/cnary.c.obj
.PHONY : vendor/libplist/libcnary/cnary.obj

# target to build an object file
vendor/libplist/libcnary/cnary.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/libcnary/cnary.c.obj
.PHONY : vendor/libplist/libcnary/cnary.c.obj

vendor/libplist/libcnary/cnary.i: vendor/libplist/libcnary/cnary.c.i
.PHONY : vendor/libplist/libcnary/cnary.i

# target to preprocess a source file
vendor/libplist/libcnary/cnary.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/libcnary/cnary.c.i
.PHONY : vendor/libplist/libcnary/cnary.c.i

vendor/libplist/libcnary/cnary.s: vendor/libplist/libcnary/cnary.c.s
.PHONY : vendor/libplist/libcnary/cnary.s

# target to generate assembly for a file
vendor/libplist/libcnary/cnary.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/libcnary/cnary.c.s
.PHONY : vendor/libplist/libcnary/cnary.c.s

vendor/libplist/libcnary/node.obj: vendor/libplist/libcnary/node.c.obj
.PHONY : vendor/libplist/libcnary/node.obj

# target to build an object file
vendor/libplist/libcnary/node.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/libcnary/node.c.obj
.PHONY : vendor/libplist/libcnary/node.c.obj

vendor/libplist/libcnary/node.i: vendor/libplist/libcnary/node.c.i
.PHONY : vendor/libplist/libcnary/node.i

# target to preprocess a source file
vendor/libplist/libcnary/node.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/libcnary/node.c.i
.PHONY : vendor/libplist/libcnary/node.c.i

vendor/libplist/libcnary/node.s: vendor/libplist/libcnary/node.c.s
.PHONY : vendor/libplist/libcnary/node.s

# target to generate assembly for a file
vendor/libplist/libcnary/node.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/libcnary/node.c.s
.PHONY : vendor/libplist/libcnary/node.c.s

vendor/libplist/libcnary/node_list.obj: vendor/libplist/libcnary/node_list.c.obj
.PHONY : vendor/libplist/libcnary/node_list.obj

# target to build an object file
vendor/libplist/libcnary/node_list.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/libcnary/node_list.c.obj
.PHONY : vendor/libplist/libcnary/node_list.c.obj

vendor/libplist/libcnary/node_list.i: vendor/libplist/libcnary/node_list.c.i
.PHONY : vendor/libplist/libcnary/node_list.i

# target to preprocess a source file
vendor/libplist/libcnary/node_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/libcnary/node_list.c.i
.PHONY : vendor/libplist/libcnary/node_list.c.i

vendor/libplist/libcnary/node_list.s: vendor/libplist/libcnary/node_list.c.s
.PHONY : vendor/libplist/libcnary/node_list.s

# target to generate assembly for a file
vendor/libplist/libcnary/node_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/libcnary/node_list.c.s
.PHONY : vendor/libplist/libcnary/node_list.c.s

vendor/libplist/src/base64.obj: vendor/libplist/src/base64.c.obj
.PHONY : vendor/libplist/src/base64.obj

# target to build an object file
vendor/libplist/src/base64.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/base64.c.obj
.PHONY : vendor/libplist/src/base64.c.obj

vendor/libplist/src/base64.i: vendor/libplist/src/base64.c.i
.PHONY : vendor/libplist/src/base64.i

# target to preprocess a source file
vendor/libplist/src/base64.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/base64.c.i
.PHONY : vendor/libplist/src/base64.c.i

vendor/libplist/src/base64.s: vendor/libplist/src/base64.c.s
.PHONY : vendor/libplist/src/base64.s

# target to generate assembly for a file
vendor/libplist/src/base64.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/base64.c.s
.PHONY : vendor/libplist/src/base64.c.s

vendor/libplist/src/bplist.obj: vendor/libplist/src/bplist.c.obj
.PHONY : vendor/libplist/src/bplist.obj

# target to build an object file
vendor/libplist/src/bplist.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/bplist.c.obj
.PHONY : vendor/libplist/src/bplist.c.obj

vendor/libplist/src/bplist.i: vendor/libplist/src/bplist.c.i
.PHONY : vendor/libplist/src/bplist.i

# target to preprocess a source file
vendor/libplist/src/bplist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/bplist.c.i
.PHONY : vendor/libplist/src/bplist.c.i

vendor/libplist/src/bplist.s: vendor/libplist/src/bplist.c.s
.PHONY : vendor/libplist/src/bplist.s

# target to generate assembly for a file
vendor/libplist/src/bplist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/bplist.c.s
.PHONY : vendor/libplist/src/bplist.c.s

vendor/libplist/src/bytearray.obj: vendor/libplist/src/bytearray.c.obj
.PHONY : vendor/libplist/src/bytearray.obj

# target to build an object file
vendor/libplist/src/bytearray.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/bytearray.c.obj
.PHONY : vendor/libplist/src/bytearray.c.obj

vendor/libplist/src/bytearray.i: vendor/libplist/src/bytearray.c.i
.PHONY : vendor/libplist/src/bytearray.i

# target to preprocess a source file
vendor/libplist/src/bytearray.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/bytearray.c.i
.PHONY : vendor/libplist/src/bytearray.c.i

vendor/libplist/src/bytearray.s: vendor/libplist/src/bytearray.c.s
.PHONY : vendor/libplist/src/bytearray.s

# target to generate assembly for a file
vendor/libplist/src/bytearray.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/bytearray.c.s
.PHONY : vendor/libplist/src/bytearray.c.s

vendor/libplist/src/hashtable.obj: vendor/libplist/src/hashtable.c.obj
.PHONY : vendor/libplist/src/hashtable.obj

# target to build an object file
vendor/libplist/src/hashtable.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/hashtable.c.obj
.PHONY : vendor/libplist/src/hashtable.c.obj

vendor/libplist/src/hashtable.i: vendor/libplist/src/hashtable.c.i
.PHONY : vendor/libplist/src/hashtable.i

# target to preprocess a source file
vendor/libplist/src/hashtable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/hashtable.c.i
.PHONY : vendor/libplist/src/hashtable.c.i

vendor/libplist/src/hashtable.s: vendor/libplist/src/hashtable.c.s
.PHONY : vendor/libplist/src/hashtable.s

# target to generate assembly for a file
vendor/libplist/src/hashtable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/hashtable.c.s
.PHONY : vendor/libplist/src/hashtable.c.s

vendor/libplist/src/plist.obj: vendor/libplist/src/plist.c.obj
.PHONY : vendor/libplist/src/plist.obj

# target to build an object file
vendor/libplist/src/plist.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/plist.c.obj
.PHONY : vendor/libplist/src/plist.c.obj

vendor/libplist/src/plist.i: vendor/libplist/src/plist.c.i
.PHONY : vendor/libplist/src/plist.i

# target to preprocess a source file
vendor/libplist/src/plist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/plist.c.i
.PHONY : vendor/libplist/src/plist.c.i

vendor/libplist/src/plist.s: vendor/libplist/src/plist.c.s
.PHONY : vendor/libplist/src/plist.s

# target to generate assembly for a file
vendor/libplist/src/plist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/plist.c.s
.PHONY : vendor/libplist/src/plist.c.s

vendor/libplist/src/ptrarray.obj: vendor/libplist/src/ptrarray.c.obj
.PHONY : vendor/libplist/src/ptrarray.obj

# target to build an object file
vendor/libplist/src/ptrarray.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/ptrarray.c.obj
.PHONY : vendor/libplist/src/ptrarray.c.obj

vendor/libplist/src/ptrarray.i: vendor/libplist/src/ptrarray.c.i
.PHONY : vendor/libplist/src/ptrarray.i

# target to preprocess a source file
vendor/libplist/src/ptrarray.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/ptrarray.c.i
.PHONY : vendor/libplist/src/ptrarray.c.i

vendor/libplist/src/ptrarray.s: vendor/libplist/src/ptrarray.c.s
.PHONY : vendor/libplist/src/ptrarray.s

# target to generate assembly for a file
vendor/libplist/src/ptrarray.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/ptrarray.c.s
.PHONY : vendor/libplist/src/ptrarray.c.s

vendor/libplist/src/time64.obj: vendor/libplist/src/time64.c.obj
.PHONY : vendor/libplist/src/time64.obj

# target to build an object file
vendor/libplist/src/time64.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/time64.c.obj
.PHONY : vendor/libplist/src/time64.c.obj

vendor/libplist/src/time64.i: vendor/libplist/src/time64.c.i
.PHONY : vendor/libplist/src/time64.i

# target to preprocess a source file
vendor/libplist/src/time64.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/time64.c.i
.PHONY : vendor/libplist/src/time64.c.i

vendor/libplist/src/time64.s: vendor/libplist/src/time64.c.s
.PHONY : vendor/libplist/src/time64.s

# target to generate assembly for a file
vendor/libplist/src/time64.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/time64.c.s
.PHONY : vendor/libplist/src/time64.c.s

vendor/libplist/src/xplist.obj: vendor/libplist/src/xplist.c.obj
.PHONY : vendor/libplist/src/xplist.obj

# target to build an object file
vendor/libplist/src/xplist.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/xplist.c.obj
.PHONY : vendor/libplist/src/xplist.c.obj

vendor/libplist/src/xplist.i: vendor/libplist/src/xplist.c.i
.PHONY : vendor/libplist/src/xplist.i

# target to preprocess a source file
vendor/libplist/src/xplist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/xplist.c.i
.PHONY : vendor/libplist/src/xplist.c.i

vendor/libplist/src/xplist.s: vendor/libplist/src/xplist.c.s
.PHONY : vendor/libplist/src/xplist.s

# target to generate assembly for a file
vendor/libplist/src/xplist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libraop.dir/build.make CMakeFiles/libraop.dir/vendor/libplist/src/xplist.c.s
.PHONY : vendor/libplist/src/xplist.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... libraop"
	@echo "... python/bindings.obj"
	@echo "... python/bindings.i"
	@echo "... python/bindings.s"
	@echo "... src/aexcl_lib.obj"
	@echo "... src/aexcl_lib.i"
	@echo "... src/aexcl_lib.s"
	@echo "... src/alac_wrapper.obj"
	@echo "... src/alac_wrapper.i"
	@echo "... src/alac_wrapper.s"
	@echo "... src/base64.obj"
	@echo "... src/base64.i"
	@echo "... src/base64.s"
	@echo "... src/dmap.obj"
	@echo "... src/dmap.i"
	@echo "... src/dmap.s"
	@echo "... src/raop_client.obj"
	@echo "... src/raop_client.i"
	@echo "... src/raop_client.s"
	@echo "... src/rtsp_client.obj"
	@echo "... src/rtsp_client.i"
	@echo "... src/rtsp_client.s"
	@echo "... src/srp.obj"
	@echo "... src/srp.i"
	@echo "... src/srp.s"
	@echo "... tools/log_util.obj"
	@echo "... tools/log_util.i"
	@echo "... tools/log_util.s"
	@echo "... vendor/alac/codec/ALACBitUtilities.obj"
	@echo "... vendor/alac/codec/ALACBitUtilities.i"
	@echo "... vendor/alac/codec/ALACBitUtilities.s"
	@echo "... vendor/alac/codec/ALACDecoder.obj"
	@echo "... vendor/alac/codec/ALACDecoder.i"
	@echo "... vendor/alac/codec/ALACDecoder.s"
	@echo "... vendor/alac/codec/ALACEncoder.obj"
	@echo "... vendor/alac/codec/ALACEncoder.i"
	@echo "... vendor/alac/codec/ALACEncoder.s"
	@echo "... vendor/alac/codec/EndianPortable.obj"
	@echo "... vendor/alac/codec/EndianPortable.i"
	@echo "... vendor/alac/codec/EndianPortable.s"
	@echo "... vendor/alac/codec/ag_dec.obj"
	@echo "... vendor/alac/codec/ag_dec.i"
	@echo "... vendor/alac/codec/ag_dec.s"
	@echo "... vendor/alac/codec/ag_enc.obj"
	@echo "... vendor/alac/codec/ag_enc.i"
	@echo "... vendor/alac/codec/ag_enc.s"
	@echo "... vendor/alac/codec/dp_dec.obj"
	@echo "... vendor/alac/codec/dp_dec.i"
	@echo "... vendor/alac/codec/dp_dec.s"
	@echo "... vendor/alac/codec/dp_enc.obj"
	@echo "... vendor/alac/codec/dp_enc.i"
	@echo "... vendor/alac/codec/dp_enc.s"
	@echo "... vendor/alac/codec/matrix_dec.obj"
	@echo "... vendor/alac/codec/matrix_dec.i"
	@echo "... vendor/alac/codec/matrix_dec.s"
	@echo "... vendor/alac/codec/matrix_enc.obj"
	@echo "... vendor/alac/codec/matrix_enc.i"
	@echo "... vendor/alac/codec/matrix_enc.s"
	@echo "... vendor/curve25519/source/curve25519_dh.obj"
	@echo "... vendor/curve25519/source/curve25519_dh.i"
	@echo "... vendor/curve25519/source/curve25519_dh.s"
	@echo "... vendor/curve25519/source/curve25519_mehdi.obj"
	@echo "... vendor/curve25519/source/curve25519_mehdi.i"
	@echo "... vendor/curve25519/source/curve25519_mehdi.s"
	@echo "... vendor/curve25519/source/curve25519_order.obj"
	@echo "... vendor/curve25519/source/curve25519_order.i"
	@echo "... vendor/curve25519/source/curve25519_order.s"
	@echo "... vendor/curve25519/source/curve25519_utils.obj"
	@echo "... vendor/curve25519/source/curve25519_utils.i"
	@echo "... vendor/curve25519/source/curve25519_utils.s"
	@echo "... vendor/curve25519/source/custom_blind.obj"
	@echo "... vendor/curve25519/source/custom_blind.i"
	@echo "... vendor/curve25519/source/custom_blind.s"
	@echo "... vendor/curve25519/source/ed25519_sign.obj"
	@echo "... vendor/curve25519/source/ed25519_sign.i"
	@echo "... vendor/curve25519/source/ed25519_sign.s"
	@echo "... vendor/curve25519/source/ed25519_verify.obj"
	@echo "... vendor/curve25519/source/ed25519_verify.i"
	@echo "... vendor/curve25519/source/ed25519_verify.s"
	@echo "... vendor/libplist/libcnary/cnary.obj"
	@echo "... vendor/libplist/libcnary/cnary.i"
	@echo "... vendor/libplist/libcnary/cnary.s"
	@echo "... vendor/libplist/libcnary/node.obj"
	@echo "... vendor/libplist/libcnary/node.i"
	@echo "... vendor/libplist/libcnary/node.s"
	@echo "... vendor/libplist/libcnary/node_list.obj"
	@echo "... vendor/libplist/libcnary/node_list.i"
	@echo "... vendor/libplist/libcnary/node_list.s"
	@echo "... vendor/libplist/src/base64.obj"
	@echo "... vendor/libplist/src/base64.i"
	@echo "... vendor/libplist/src/base64.s"
	@echo "... vendor/libplist/src/bplist.obj"
	@echo "... vendor/libplist/src/bplist.i"
	@echo "... vendor/libplist/src/bplist.s"
	@echo "... vendor/libplist/src/bytearray.obj"
	@echo "... vendor/libplist/src/bytearray.i"
	@echo "... vendor/libplist/src/bytearray.s"
	@echo "... vendor/libplist/src/hashtable.obj"
	@echo "... vendor/libplist/src/hashtable.i"
	@echo "... vendor/libplist/src/hashtable.s"
	@echo "... vendor/libplist/src/plist.obj"
	@echo "... vendor/libplist/src/plist.i"
	@echo "... vendor/libplist/src/plist.s"
	@echo "... vendor/libplist/src/ptrarray.obj"
	@echo "... vendor/libplist/src/ptrarray.i"
	@echo "... vendor/libplist/src/ptrarray.s"
	@echo "... vendor/libplist/src/time64.obj"
	@echo "... vendor/libplist/src/time64.i"
	@echo "... vendor/libplist/src/time64.s"
	@echo "... vendor/libplist/src/xplist.obj"
	@echo "... vendor/libplist/src/xplist.i"
	@echo "... vendor/libplist/src/xplist.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

